### ISSUE TITLE
Can you have a placeholder value for the filters if you do not have a search value

### ISSUE THREAD

**Issue by craigkai** [dasDaniel/svelte-table#144]
I'd like to have a placeholder value for the search filters but I still only want the input to be a select input and not allow typing in values. I tried adding a value to my filterOptions with a placeholder name and undefined value but that doesn't seem to work:
```js
values.push({
		name: 'all',
		value: undefined
	});
return values;
```

**Comment by raja611** [comment]
Hello @craigkai ,

I understand the problem, the problem is at - https://github.com/dasDaniel/svelte-table/blob/develop/src/SvelteTable.svelte#L319 .

since the first option value is undefined, the filters have no placeholder value if you do not have a search value.

Update the above-mentioned line of code to  `<option value="All" />`

It will give value to filterOptions for the placeholder without any empty value.

Thank you.

**Comment by dasDaniel** [comment]
I've updated the `filterPlaceholder` to work on the dropdowns too
