### ISSUE TITLE
Dynamically Populated Value Option 

### ISSUE THREAD

**Issue by lrpatterson** [dasDaniel/svelte-table#17]
Working to dynamically create columns.  Seems like I should be able to either set the `value` option by  doing ` value: v => v[Object.keys(data[0])[i]]`  but it raises an error (`Cannot read property 'keys' of undefined`).  Is there a way to set the value option dynamically?

```
response.then(function(data){
			rows = data
			for (var i = 0; i < Object.keys(data[0]).length; i++) {
			
				columns.push({key: Object.keys(data[0])[i], title: Object.keys(data[0])[i], value: v => v[Object.keys(data[0])[i]], sortable: true})
			})
```

**Comment by dasDaniel** [comment]
the problem is that `value` is a function and you're passing variables to it that get interpreted at the time of rendering. That means that the values that make up the key are changing even after they are defined. To get around that  you could scope the key variable to the function loop, that way the value of `v: v[key]` will be predictable.

```js
for (var i = 0; i < Object.keys(data[0]).length; i++) {
  const key = Object.keys(rows[0])[i]
  columns.push({key, title: key, value: v => v[key], sortable: true})
}
```
