### ISSUE TITLE
Export package.json

### ISSUE THREAD

**Issue by js-ferguson** [dasDaniel/svelte-table#171]
After installing the package I get the following during rollup

rollup-plugin-svelte: The following packages did not export their `package.json` file so we could not check the `svelte` field. If you had difficulties importing svelte components from a package, then please contact the author and ask them to export the package.json file.
 - svelte-table

This may or may not be related to another issue. After installing and importing the package with `import SvelteTable from "svelte-table";`

`<SvelteTable columns="{columns}" rows="{rows}"></SvelteTable>`

I get the following in the browser console

```
Uncaught TypeError: u is undefined
    Z SvelteTable.mjs:1
    Te SvelteTable.mjs:1
    create_fragment$x bundle.js:25683
    init index.mjs:2180
    IncomingList bundle.js:26075
    create_fragment$8 bundle.js:39000
    init index.mjs:2180
    Incoming_1 bundle.js:39085
    construct_svelte_component_dev index.mjs:2398
    create_then_block$3 bundle.js:2186
    update index.mjs:1655
    handle_promise index.mjs:1708
    create_if_block_1$e bundle.js:2088
    create_if_block$n bundle.js:1947
    update bundle.js:2306
    update index.mjs:1347
    flush index.mjs:1307
    init index.mjs:2197
    App bundle.js:41608
    app main.js:3
    <anonymous> bundle.js:41626
[SvelteTable.mjs:1:4628](http://localhost:9000/static/node_modules/svelte-table/dist/es/SvelteTable.mjs)
```

**Comment by dasDaniel** [comment]
try updating `rollup-plugin-svelte` to `^7.2.0`

There's a good description of the issue here https://stackoverflow.com/questions/69768925/rollup-plugin-svelte-the-following-packages-did-not-export-their-package-json  and a PR here https://github.com/sveltejs/rollup-plugin-svelte/pull/205

The package.json file has changed a bit in the last couple versions to accommodate both vite and sveltekit, but the older version of rollup-plugin-svelte handles it differently, but bottom line is that updating it will most likely resolve it for you.
