### ISSUE TITLE
How to group columns visually

### ISSUE THREAD

**Issue by flooyd** [dasDaniel/svelte-table#55]
I am loving svelte-table so far and find it easy to use, but I need some help with this.

I am making something for a game and I want three columns (Kills, Deaths, Assists).

Currently I have one column (KDA), with a value of v.kills + '/' + v.deaths + '/' + v.assists.

Obviously I can't sort on all three fields using that one column, but if I split them up into separate columns, the content will no longer be visually grouped together. How do I solve this? Thanks for svelte-table and any help!

### Current

Player          KDA          Other

### With separate columns

Player          K          D          A          Other

I want it to visually look like the former using separate columns so I can sort on each field.

**Comment by dasDaniel** [comment]
there's a 1:1 mapping between the `column[n].value` and the `sortOn`  so the one column has to use the same function for generating the sort order. However, since it is a function, you can have the sort key managed externally.

so instead of using `value: v => v.kills + '/' + v.deaths + '/' + v.assists` you can use `value: v => v[sortKey]` where the `sortKey` is managed by the table parent component. Then use `renderValue` for having the consistent look. 

The reactivity will not kick in on t he change of the value though, so you'll need to manually trigger it. I would use `sortOrder` &&|| `sortBy` to trigger the reactivity, but a key would work too.

[example repo](https://svelte.dev/repl/545b78fb6da748f39bc8c27d90c9cd4b)
