### ISSUE TITLE
Expanded row is included in striped css

### ISSUE THREAD

**Issue by feAnnamari** [dasDaniel/svelte-table#79]
Hello! 

I want to create a striped table, but if I add the corresponding class to the *classNameRow* or *classNameTable* property the expanded part is also counted as odd or even row. This way if I'm expanding a row, the stripe colors are shifting.

Is there any workaround, to skip the expanded row when striping the table?

Here is a REPL showing my issue: https://svelte.dev/repl/1e2ceb9912c5415ba929570382c5a772?version=3.46.4

Thank you

**Comment by dasDaniel** [comment]
unfortunately, that's not possible at the moment.

A bootstrap css based solution would need a way to skip a row, which the css would not be able to handle. So the row would need to have the ability to dynamically set a class name based on the row index. this is currently not possible since the row class only accepts strings at the moment. It would be feasible to implement accepting functions as row class names, which would be able to handle that.

Until that is implemented, the only solution I can think of is to use the `row` slot. The issue, obviously, is that it would leave a lot of the functionality to implement. For example, because the data passed to the template is not mutable, even the expand functionality would have to be re-implemented. 

here's what that might look like 

```html<script>
  // ...skipped
  let data = []; // use let to allow mutability

  let generateData = () => {
    data = Array(numRows)
      .fill("")
      .map((n, i) => {
        let d = {
          expanded: false,  // make available in row data
          id: i,
          first_name: faker.name.firstName(),
          last_name: faker.name.lastName(),
        };
        d.email =
          d.first_name[0].toLowerCase() +
          d.last_name.toLowerCase() +
          "@zipit.org.ca";
        return d;
      });
  };

  const COLUMNS = {
    // ...skipped
  };

  // allow toggling visibility
  function toggleExpanded(rowId) {
    data = data.map(r => {
      if (r.id == rowId) r.expanded = !r.expanded;
      return r;
    });
  }

 // ...more skipped
</script>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.0-alpha1/css/bootstrap.min.css"/>

<div class="container">
  <h1>SvelteTable Example 4</h1>
  <p>Shows that filters are reactive</p>
  <div class="input-group pb-3">
    <button class="btn btn-primary" on:click={generateData}>
      Generate Data
    </button>
    <input bind:value={numRows} class="form-control" />

    <button
      class="btn btn-primary"
      on:click={() => {
        sortOrder = 1;
      }}
      disabled={sortOrder === 1}
      style="float:right;"
    >
      SORT {iconAsc}
    </button>
    <button
      class="btn btn-primary"
      on:click={() => {
        sortOrder = -1;
      }}
      disabled={sortOrder === -1}
      style="float:right;"
    >
      SORT {iconDesc}
    </button>
  </div>

  <div class="row">
    <SvelteTable
      columns={cols}
      showExpandIcon={true}
      rows={data}
      bind:sortBy
      bind:sortOrder
      classNameTable={["table"]}
      classNameThead={["table-primary"]}
      classNameSelect={["custom-select"]}
    >
      <svelte:fragment slot="row" let:row let:n>
        <tr class:tr-odd={n % 2}>
          <td>{row.id}</td>
          <td>{row.first_name}</td>
          <td>{row.last_name}</td>
          <td>{row.email}</td>
          <td>
            <button
              class="btn btn-outline-secondary btn-sm"
              on:click={() => toggleExpanded(row.id)}
              >{row.expanded ? "collapse" : "expand"}</button
            >
          </td>
        </tr>
        {#if row.expanded}
          <tr>
            <td colspan="5">
              <p>Hello</p>
            </td>
          </tr>
        {/if}
      </svelte:fragment>
    </SvelteTable>
  </div>
</div>

<style>
  :global(tr.tr-odd) {
    background-color: #f2f2f2;
  }
</style>
```

* this uses the `n` parameter passed with modulo to determine if row is even or odd (on a 0-based index in example)
* custom class `.tr-odd` for changing color
* uses button for toggling `expanded` state
* uses `expanded` state to determine whether extended should be shown.

**Comment by dasDaniel** [comment]
added ability to handle row and cell class in v0.4.0 #90
